FROM nginx:alpine

# Copy the self-signed certificate and private key
COPY nginx-selfsigned.crt /etc/nginx/nginx-selfsigned.crt
COPY nginx-selfsigned.key /etc/nginx/nginx-selfsigned.key

# Copy the custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf